### PR TITLE
Add unique open graph metadata to pages

### LINKED ISSUE #12: Add unique open graph metadata to pages
Unique OG metadata should be added to each page so that they properly display when shared ([why](https://ahrefs.com/blog/open-graph-meta-tags/)).

### PR DESCRIPTION
**Pull request by wbnns**
Resolves #12.

### CODE REVIEW

**Comment by CesarCoelho** [comment]
Many thanks for the PR.
You used a slash in the title, is there a particular reason for not using a dash or pipe?
Typically in websites, I see in the title the dash or pipe, are these title metatags for social media somehow different?

(I am asking because I am not an expert in SEO)

**Comment by wbnns** [comment]
@CesarCoelho 

Sure thing, happy to help. RE: slash vs dash or pipe, no, that's just a personal preference -- I can change it to a dash or pipe if you prefer one or the other. The main thing is that for SEO there should be a separator (slash/dash/pipe/wingding/etc) between the primary keyword/keyphrase (what the page is about) and secondary keyword/keyphrase (what the site is about).

**Comment by CesarCoelho** [comment]
Alright, can you change it to the dash notation, then? I believe it will look better.
I was trying to edit here directly on GitHub but didn't manage to figure it out.

**Comment by wbnns** [comment]
@CesarCoelho 

Sure thing, done: cfbe0dc

**Comment by CesarCoelho** [comment]
Perfect, thanks!

**Pull request merged**
